version: "3.3"
services:
  app:
    container_name: "${NAME}"
    image: "${NAME}"
    restart: always
    build:
      context: .
    volumes:
      - ./logs:/var/www/html/logs  # Логи приложения будут сохраняться в локальную папку
    ports:
      - "${PORTS}"
    environment:
      DOMAIN: "${DOMAIN}"
    env_file:
      - .env
    logging: # Добавляем логирование в AWS
      driver: awslogs
      options:
        awslogs-group: "${AWS_LOG_GROUP}" # Название группы логов
        awslogs-region: "${AWS_REGION}"  # Регион AWS
        awslogs-stream: "support-time-elest.io/access.log"   # Поток логов для контейнера
  support-time-app-log:
    image: busybox
    volumes:
      - ./logs:/var/www/html/logs
    logging:
      driver: awslogs
      options:
        awslogs-group: "${AWS_LOG_GROUP}"
        awslogs-stream: "support-time-elest.io/app.log"
        awslogs-region: "${AWS_REGION}"
        awslogs-create-group: "true"
    command: tail -f /var/www/html/logs/app.log